import mongoose from "mongoose";
import config from "../../config";
import { TStudentData } from "../Student/student.interface";

import { AcademicModel } from "../academicSemester/academicSemModel";
import { Student } from "../Student/student.model";
import { TUser, newUser } from "./user.interface";
import { userModel } from "./user.model";
import {
  generateAdminId,
  generateFacultyId,
  generatedStudentId,
} from "./user.utils";
import AppError from "../../errors/AppError";
import httpStatus from "http-status";
import { TFaculty } from "../Faculty/Faculty.interface";
import { AcademicDepartModel } from "../academicDepartment/department.model";
import { Faculty } from "../Faculty/Faculty.model";
import { TAdmin } from "../Admin/Admin.interface";
import { Admin } from "../Admin/Admin.model";

const createStudentIntDB = async (password: string, payload: TStudentData) => {
  //now we will call Student Model
  const userData: Partial<TUser> = {};
  if (!password) {
    userData.password = config.defaultPass as string;
  } else {
    userData.password = password;
  }

  //set the role
  userData.role = "student";
  //set the manually id
  const admissionSemester = await AcademicModel.findById(
    payload.admissionSemesterId
  );

  const session = await mongoose.startSession();
  try {
    session.startTransaction();
    //set generated by id function
    if (admissionSemester) {
      userData.id = await generatedStudentId(admissionSemester);
    } else {
      throw new Error("Not Found ID");
    }
    const newUser = await userModel.create([userData], { session }); // to get an array
    if (!newUser.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create a user");
    }
    payload.id = newUser[0].id;
    payload.user = newUser[0]._id; // reference ID

    const newStudent = await Student.create([payload], { session }); // to get an array

    if (!newStudent.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create student");
    }

    await session.commitTransaction();
    await session.endSession();

    return newStudent;
  } catch (err) {
    await session.abortTransaction();
    await session.endSession();
    throw new Error("Failed to create student");
  }
};
const createFacultyIntoDB = async (password: string, payload: TFaculty) => {
  // create a user object
  const userData: Partial<TUser> = {};

  //if password is not given , use deafult password
  userData.password = password || (config.defaultPass as string);

  //set student role
  userData.role = "faculty";

  // find academic department info
  const academicDepartment = await AcademicDepartModel.findById(
    payload.academicDepartment
  );

  if (!academicDepartment) {
    throw new AppError(400, "Academic department not found");
  }

  const session = await mongoose.startSession();

  try {
    session.startTransaction();
    //set  generated id
    userData.id = await generateFacultyId();

    // create a user (transaction-1)
    const newUser = await userModel.create([userData], { session }); // array

    //create a faculty
    if (!newUser.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create user");
    }
    // set id , _id as user
    payload.id = newUser[0].id;
    payload.user = newUser[0]._id; //reference _id

    // create a faculty (transaction-2)

    const newFaculty = await Faculty.create([payload], { session });

    if (!newFaculty.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create faculty");
    }

    await session.commitTransaction();
    await session.endSession();

    return newFaculty;
  } catch (err: any) {
    await session.abortTransaction();
    await session.endSession();
    throw new Error(err);
  }
};
const createAdminIntoDB = async (password: string, payload: TAdmin) => {
  // create a user object
  const userData: Partial<TUser> = {};

  //if password is not given , use deafult password
  userData.password = password || (config.defaultPass as string);

  //set student role
  userData.role = "admin";

  const session = await mongoose.startSession();

  try {
    session.startTransaction();
    //set  generated id
    userData.id = await generateAdminId();

    // create a user (transaction-1)
    const newUser = await userModel.create([userData], { session });

    //create a admin
    if (!newUser.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create admin");
    }
    // set id , _id as user
    payload.id = newUser[0].id;
    payload.user = newUser[0]._id; //reference _id

    // create a admin (transaction-2)
    const newAdmin = await Admin.create([payload], { session });

    if (!newAdmin.length) {
      throw new AppError(httpStatus.BAD_REQUEST, "Failed to create admin");
    }

    await session.commitTransaction();
    await session.endSession();

    return newAdmin;
  } catch (err: any) {
    await session.abortTransaction();
    await session.endSession();
    throw new Error(err);
  }
};

export const userService = {
  createStudentIntDB,
  createFacultyIntoDB,
  createAdminIntoDB,
};
