import config from "../../config";
import { TStudentData } from "../Student/student.interface";
import { academicServices } from "../academicSemester/academic.services";
import { AcademicModel } from "../academicSemester/academicSemModel";
import { Student } from "../student.model";
import { TUser, newUser } from "./user.interface";
import { userModel } from "./user.model";
import { generatedStudentId } from "./user.utils";

const createStudentIntDB = async (password: string, payload: TStudentData) => {
  //now we will call Student Model
  const userData: Partial<TUser> = {};
  if (!password) {
    userData.password = config.defaultPass as string;
  } else {
    userData.password = password;
  }

  //set the role
  userData.role = "student";
  //set the manually id
  const admissionSemester = await AcademicModel.findById(
    payload.admissionSemesterId
  );
  //set generated by id function
  if (admissionSemester) {
    userData.id = await generatedStudentId(admissionSemester);
  } else {
    throw new Error("Not Found ID");
  }
  const newUser = await userModel.create(userData);
  if (Object.keys(newUser).length) {
    //set id as user
    payload.id = newUser.id;
    payload.user = newUser._id;
    const newStudent = await Student.create(payload);
    return newStudent;
  }
  return newUser;
  //make data push using instance
  //   const student = new Student(studentData);
  //   if (await student.isUserExists(studentData.id)) {
  //     throw new Error(`Student already exists`);
  //   }
  //   const result = await student.save();
  //   return result;
  // };
};
export const userService = {
  createStudentIntDB,
};
